// <auto-generated />
using System;
using Hadrian.CodingAssignment.Infrastructure.Data.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hadrian.CodingAssignment.Infrastructure.Migrations
{
    [DbContext(typeof(HadrianDbContext))]
    partial class HadrianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<string>("IntegrationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("integration_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NotifyWhenAssetIsFound")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_when_asset_is_found");

                    b.Property<bool>("NotifyWhenRiskIsFound")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_when_risk_is_found");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_integrations_organization_id");

                    b.ToTable("integrations", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Integration");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.MsTeamsIntegration", b =>
                {
                    b.HasBaseType("Hadrian.CodingAssignment.Infrastructure.Model.Integration");

                    b.Property<string>("Webhook")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("webhook");

                    b.ToTable("integrations", (string)null);

                    b.HasDiscriminator().HasValue("MsTeamsIntegration");
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.Integration", b =>
                {
                    b.HasOne("Hadrian.CodingAssignment.Infrastructure.Model.Organization", "Organization")
                        .WithMany("Integrations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.User", b =>
                {
                    b.HasOne("Hadrian.CodingAssignment.Infrastructure.Model.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Hadrian.CodingAssignment.Infrastructure.Model.Organization", b =>
                {
                    b.Navigation("Integrations");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
